### ISSUE TITLE
Investigate parallelizing builds

### ISSUE THREAD

**Issue by wearhere** [mixmaxhq/multibuild#2]
Now that https://github.com/rollup/rollup/issues/1010 is fixed it should be possible, but I'm unsure if running the builds in parallel will outweigh the advantage of reusing the cache between builds as made possible by running in serial.

If the overhead of running individual target builds (i.e. starting up rollup) is greater than the savings of reusing a single module's cache, we might do something like do [the initial build](https://github.com/mixmaxhq/multibuild/blob/master/index.js#L58) in serial, then run [the change builds](https://github.com/mixmaxhq/multibuild/blob/master/index.js#L77) in parallel.

**Comment by spencer-brown** [comment]
Local testing suggests that parallelizing does not speed up initial builds or incremental builds.

For reference, parallelization was tested in (in `changed`) like this:
```js
changedTargetTasks.forEach((taskName) => {
  this._gulp.start.apply(this._gulp, [taskName]);
});

let taskCompletionCount = 0;
const onStop = () => {
  taskCompletionCount += 1;

  // Gets the job done :P
  if (taskCompletionCount === changedTargetTasks.length) {
    this._gulp.removeListener('task_stop', onStop);
    this._gulp.removeListener('task_err', done);
    done();
  }
};

this._gulp.on('task_stop', onStop);
this._gulp.on('task_err', done);
```
